# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    - name: Restore dependencies
      run: dotnet restore src/UnEntityFrameworkRepository.sln
    - name: Build
      run: dotnet build src/UnEntityFrameworkRepository/UnEntityFrameworkRepository.csproj --configuration Release --no-restore
    - name: Pack Nuget Package
      run: dotnet pack src/UnEntityFrameworkRepository/UnEntityFrameworkRepository.csproj /p:Version=${{github.event.release.tag_name}} --output nuget-published --configuration Release
    - name: Publish Nuget Package
      run: dotnet nuget push ****/nuget-published/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
